### ISSUE TITLE
Illuria Levelling Guide

### ISSUE THREAD

**Issue by Illuren** [superarts/superarts.github.io#7]
## About

This page is a simplified version of [this guide](https://www.poe-vault.com/guides/quick-reference-leveling-guide-act-8). I'm not going to explain my convention here but roughly speaking it's always about "to go where" and "to do what", so it assumes you already leveled up once or twice at least and know what you are doing.

Combining with [Tytykiller's Absolution leveling guide](https://github.com/superarts/superarts.github.io/issues/4)

## How to use

- Copy markdown to a page that you have edit privilege
- Use it as a checklist will modify your page, so don't edit your original copy

## Act 1

- [x] Make a Scion, do the prologue, stash, Onslaught

### Reset

- [x] Twilight Strand: kill `Hillock`
- [x] Lioneye's Watch: Tarkleigh `gem`
  - [x] Level 2: Buy `BBG` `BBB` `RGB`
  - [x] `BBG`: Freezing Pulse (B), Onslaught (G), Arcane Surge (B)
- [x] The Coast: midway `waypoint`
  - [x] OPTIONAL (side) Tidal Island: kill `Hailrake` logout; Nessa `flask`
- [x] The Mud Flats: get `Glyph x 3`, glyph wall; Tarkleigh `gem`
  - Level 4
  - [x] `BBG` Freezing Pulse (B), Onslight (G), Frost Bomb (B)
  - [x] `BBB` Frostblink (B), Arcane Surge (B)
  - [x] `RGB` Holy Flame Totem (R) - Phantasm Suppport (B)
- [x] Submerged Passage: `waypoint`:
  - [x] (bottom) Flooded Depth: kill `Deep Dweller` logout; Tarkleigh `skill`
- [x] The Ledge: midway `waypoint`
- [x] The Climb: midway `waypoint`
- [x] Lower Prison: `waypoint`
  - [x] OPTIONAL Labyrinth
  - Level 8: crafting
    - [ ] Normal Topaz Ring + Magic Wand + Alteration = Lightning damage wand
    - [ ] Iron Ring + Green Gem = Topaz Ring
- [x] Upper Prison -> Warden’s Quarter -> Warden’s Chambers: kill `Brutus` logout; Tarkleigh `gem`
  - Level 8-10
    - [x] Added lighting damage - replace Freezing Pulse or Frost Bomb (useful for Brutus)
- [x] Prisoner's Gate: auto `waypoint`
  - Level 12
    - [x] `RGB`: Absolution, Onslaught, Added Lighting
    - [x] `BBB`: Flame dash, arcane surge
    - [x] Holy Flame Totem, Summon Phantasm
    - [x] Flame wall
    - [x] Spirit offering
- [x] Ship Graveyard: close by `waypoint`
  - [x] Ship Graveyard Cave: get `Allflame` logout
  - [x] Ship Graveyard: kill `Fairgraves`
- [x] Cavern of Wrath -> Cavern of Anger -> kill `Merveil` logout; Bestel `skill`; Nessa `gem`
- [x] Southern Forest: auto `waypoint`

## Act 2

- [x] Forest Encampment
- [x] (right) Old Fields -> The Crossroads -> path midway `waypoint`
  - [x] (up) Chamber of Sins lv1: midway `waypoint`
  - [x] Chamber of Sins lv2: upper-left kill `Fidelitas`; get `Baleful Gem` logout; Greust `gem`
    - [x] OPTIONAL Labyrinth
  - [x] (right) Broken Bridge: path -> down kill `Kraityn` logout
    - [x] OPTIONAL (down) Felshrine Ruins -> The Crypt lv1: Labyrinth logout
- [x] (left) Riverways: path midway `waypoint`
  - [x] (path left) Western Forest: path midway `waypoint`
    - [x] kill `Alira`
    - [x] Weaver's Chamber -> Weaver's Nest: kill `the Weaver`; get `Maligaro’s Spike` logout; Silk `gem`
    - [x] bottom kill the `Blackguards`; get `Thaumetic Seal` logout; Act 1 Bestel `skill`
  - [x] (near) The Wetlands: upper left `waypoint`
    - [x] kill `Oak`
    - [x] close `event` -> `Vaal Ruins` -> `event`
- [x] Northern Forest -> the Caverns: midway `waypoint`
- [x] Ancient Pyramid -> Pyramid Apex: kill `Vaal Oversoul` logoout
  - [x] Act 1: `skill`
- [x] City of Sarn: auto `waypoint`; kill the `Blackguards`; Clarissa `event`

### Gem

- Level 16
  - [x] Skitterbots, Herald of Thunder, Desecrate
- Level 20
  - [x] Rare Topaz Ring + Magic Wand + Alteration = Lightning damage wand

## Act 3

- [x] (upper left) Sarn Encampment
- [x] Slums -> Crematorium: midway `waypoint`; kill `Piety`; get `Tolman’s Bracelet` logout; Clarissa `sewer key`
  - [x] OPTIONAL Labyrinth
  - [x] The Sewers: get `Platinum Bust`; waypoint; `Platinum Bust x 2`
  - Level 24
    [ ] Convocation & Convocation
- [x] Marketplace: `waypoint`
  - [x] OPTIONAL (upper right) Catacombs: Labyrinth logout
- [x] Battlefront: center `waypoint`
  - [x] (down) get `Ribbon Spool`
  - [x] (up) Solaris Temple lv1: midway `waypoint`
- [x] Solaris Temple lv2: midway `waypoint` -> Battlefront
  - [x] (upper left) Docks: get `Thaumetic Sulphite` logout; Hargen `skill`
  - [x] Lady Dialla `Infernal Talc` -> Sewers
- [x] (left) Undying Blockage
- [x] Ebony Barracks: `waypoint`; up kill `General Gravicius`
  - [x] Lunaris Temple lv1: waypoint
  - [x] Lunaris Temple lv2: (single cart) kill `Piety`; get `Tower Key` logout; Grigor `skill`; Maramoa `gem`
  - [x] (right) Imperial Gardens: path midway `waypoint`
    - [x] OPTIONAL (upper left) Library: `waypoint`; find `Loose Candle` -> Archive: `Golden Pages x 4`; waypoint
    - Level 28
      - [x] Absolution - added lightning - onslaught - controlled destruction
      - [x] Shield charge - faster attacks
      - [x] Falme dash - arcane surge
      - [x] Convocation / conductivity / Spirit Offering
    - [x] OPTIONAL (up) Labyrinth
    - [x] (path right) Sceptre of God -> Uppper Sceptre of God: kill `Dominus` logout
- [x] Trail plaza: normal Lab
- [x] Aqueduct: auto `waypoint`

## Act 4

- [ ] Highgate
- [ ] (left) The Dried Lake: kill `Voll`; get `Deshret’s Banner`; logout
- [ ] (up) The Mines lv1 -> The Mines lv2: Deshret’s Spirit `event`
- [ ] Crystal Veins: end `waypoint`
  - [ ] Kaom's Dream -> Kaom’s Stronghold: `waypoint` -> Caldera of the King: kill `Kaom` logout; Tasuni `skill`
  - [ ] Daresso's Dream: kill `Barkhul` -> The Grand Arena: `waypoint` -> The Ring of Blades: kill `Daresso` logout; event
- [ ] Belly of the Beast lv1 -> Belly of the Beast lv2 -> Bowels of the Beast: kill `Piety`
- [ ] The Harvest: `waypoint`; kill `Doedre, Maligaro, and Shavronne`
- [ ] The Black Core: kill `Malachai` logout
- [ ] (upper right) Oyun `golem gem`; Dialla `gem`; The Ascent -> Oriath Portal

## Act 5

- [ ] Slave Pens: auto `waypoint`; kill `Overseer Crow`
- [ ] Overseer's Tower:  Lani `ring`
- [ ] Control Blocks: (left) get `Miasmeter`; kill `Justicar Casticus`; get `Eyes of Zeal`
- [ ] Oriath Square: `waypoint` -> Templar Courts -> The Chamber of Innocence: `waypoint` -> The Scanctum of Innocence: kill `High Templar Avarius` and `Innocence`; get out
- [ ] Torched Courts -> Ruined Square: automatically at upper right
  - [ ] (upper left) waypoint -> Ossuary: (upper left then clockwise) get `Sign of Purity`; exit or logout
  - [ ] (bottom right) The Reliquary: (corners) get `Kitava's Torments x 3`; logout
    - [ ] Vilenta `skill`; Lani `flask`, `skill`, `jewel`
  - [ ] (mid left) Cathedral Rooftop -> Cathedral Apex: kill `Kitava` -> Lilly Roth: to `Wraeclast`

## Act 6

- [ ] OPTIONAL Twilight Strand: clear; logout; Lilly Roth: sell `gems`
  - [ ] `RBBB` Absolution (R) - Physical To Lightning (B) - Controlled Destruction (B) - Spell Echo (B)
  - [ ] `BBB` Raise Zombie (B) - Carrion Golem (B) - Feeding Frenzy (B)
  - [ ] `BB?` Raise Spectre - elemental army - minion life
  - [ ] `RG` Shield Charge (R) - Faster Attacks (G)
  - [ ] `BB` Flame Dash (B) - Arcane Surge (B)
  - Determination, Herald of Purity, Skitterbots, Desecrate and Spirit Offering
- [ ] The Coast: end `waypoint`
- [ ] Mud Flats: kill `The Dishornered Queen` (look for orange named mob); get `Eye of Conquest`
- [ ] (upper middle) Karui Fortress -> Tukohama's Keep: kill `Tokohama`; unlock Pantheon
- [ ] The Ridge: midway `waypoint`
- [ ] Lower Prison: `waypoint`
  - [ ] OPTIONAL Labyrinth
- [ ] Shavronne's Tower -> Prison Rooftop: kill `Brutus` and `Shavronne`
- [ ] Warden's Chambers -> Prisoner's Gate: `waypoint`
  - [ ] Valley of the Fire Drinker: kill `Abberath`; logout
  - [ ] Tarkleigh `skill`; Bestel `skill`
- [ ] Western Forest: path midway `waypoint`
- [ ] The Riverways: path midway `waypoint`
  - [ ] (upper) The Wetland -> Spawning Ground: kill `Puppet Mistress`; logout
  - [ ] Tarkleigh `skill`
- [ ] (middle bottom) Southern Forest: end `waypoint`
- [ ] Covern of Anger: get `Black Flag` -> Passage
- [ ] The Beacon: `waypoint`; `event` escort, light, switch; Weylam Roth: to `Brine King's Reef`
- [ ] Brine King's Reef: `waypoint`; kill Brine King; unlock Pantheon; Weylam Roth: to Act 7

## Act 7

- [ ] Broken Bridge
- [ ] (bottom left) The Crossroad: `waypoint`
  - [ ] (bottom path) Fellshrine Ruins -> The Crypt: waypoint
    - [ ] OPTIONAL Labyrinth
    - [ ] The Crypt lv2: get `Maligora's Map`; logout
  - [ ] (upper path) Chamber of Sins lv1: midway `waypoint`; use map device; Maligaro's Workshop: kill `Maligaro`; get `Black Venom`; portal
    - [ ] Silk `Obsidian Key`
    - [ ] Chamber of Sins: lv2
      - [ ] OPTIONAL Labyrinth
- [ ] The Den -> Ashen Field -> Fortress Encampment: kill `Greust`
- [ ] Northern Forest: `waypoint`
  - [ ] OPTIONAL Helena `Greust's Necklace` -> Azmeri Shrine
  - [ ] The Dread Thicket -> Den of Despair: kill Gruthkul; get `Fireflies x 7`
- [ ] The Causeway: `waypoint`; get `Kishara's star`
- [ ] Vaal City: middle `waypoint`; event
  - [ ] Eramir `skill`; Weylam `skill`; OPTIONAL Helena `amulet`
- [ ] Temple of Decay lv1 -> Temple of Decay lv2 -> Akaraali's Web: kill `Arakaali` -> Sarn Ramparts

## Act 8

- [ ] Sarn Encampment
- [ ] Toxic Conduits -> Doedre's Cesspool -> The Cauldron: klll `Doedre the Vile`
- [ ] Sewer Outlet: `waypoint`
- [ ] (right) The Quay: (long bridge) `Ankh of Eternity` -> Ressurection Site: kill `Tormal`; Clarissa `talk`
- [ ] Grain Gate: `waypoint`; (upper right) kill `Gemling Legionnaires`
- [ ] Imperial Fields: path midway `waypoint`
- [ ] Solaris Temple lv1: midway `waypoint` -> Solaris Temple lv2: kill Dawn; get `Sun Orb`; logout
  - [ ] Clarissa `skill`; Maramoe `skill`; Hargen `ring`
- [ ] Toxic Conduits `waypoint -> (left) Grand Promenade
- [ ] Bath House: waypoint
  - [ ] OPTIONAL Labyrinth
  - [ ] High Gardens -> Pools of Terror: kill `Yugul`; logout
  - [ ] Hargan `skill`
- [ ] Lunaris Concourse: `waypoint`
  - [ ] Lunaris Temple lv1: `waypoint`
  - [ ] Lunaris Temple lv2: kill `Dusk`; get `Moon Orb` logout
  - [ ] (down) Harbour Bridge
- [ ] Sky Shrine: kill `Solaris and Lunaris`
- [ ] Blood Aqueducts -> Highgate

## Act 9

- [ ] The Descent: go right
- [ ] Vastiri Desert: upper right `waypoint`
  - [ ] Storm Weathered Chest -> portal -> speak PV -> speak Sin -> speak PV -> upper right The Oasis -> Sand Pit: kill `Shakari` logout; Irasha `skill`
- [ ] The Foothills: upper right `waypoint`
  - [ ] Boiling Lake: up (petrified enemies) kill `Basilisk`
- [ ] (upper left) The Tunnel: midway `waypoint`
  - [ ] OPTIONAL Labyrinth
- [ ] The Quarry: center `waypoint`
  - [ ] The Rifinery: kill `General Adus`; get `Trarthan Powder` logout
  - [ ] Shrine of the Winds: kill `Garukhan` logout; Irasha `skill`
- [ ] The Quarry -> Belly of the Beast -> Rotten Core: kill `Shavronne`, `Maligaro`, and `Doedre`
- [ ] The Black Heart: kill `Depraved Trinity`
- [ ] Lilly Roth `talk` -> Oriath

## Act 10

- [ ] Cathedral Rooftop
  - [ ] (left) Cathedral Apex: help Bannon; return; go right
- [ ] Ravaged Square: up `waypoint`
  - [ ] OPTIONAL Ossuary: Labyrinth; get `Elixir of Allure` logout; `respec`
  - [ ] (upper right) Torched Courts -> Desecrated Chambers: `waypoint`; kill `Avarius, Reassembled`; logout; Bannon `flask`; Lani `armor`
  - [ ] (buttom) Control Blocks: kill `Vilenta` logout; Lani `skill`
  - [ ] Innocent `event`
- [ ] Canals -> The Feediing Through -> Altar of Hunger: kill `Kitava`; Lani `skill`

## Ending

`/passives` to check if you have obtained all 24 skill points.

**Comment by superarts** [comment]
Closing this and let's prepare for 3.19!
